# Generated by Django 6.0.5 on 2026-06-17 11:45

from django.db import migrations, models


def copy_employer_company_details(apps, schema_editor):
    InternshipOpportunity = apps.get_model(
        'internships',
        'InternshipOpportunity'
    )

    for opportunity in InternshipOpportunity.objects.select_related('employer'):
        opportunity.company_name = opportunity.employer.company_name
        opportunity.company_email = opportunity.employer.company_email
        opportunity.save(update_fields=['company_name', 'company_email'])


def reverse_copy_employer_company_details(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_applicationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipopportunity',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='internshipopportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(
            copy_employer_company_details,
            reverse_copy_employer_company_details
        ),
    ]
