# Generated by Django 6.0.5 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_internshipopportunity_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipopportunity',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_company_images/'),
        ),
    ]
